name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitLab Repository
      uses: actions/checkout@v2
      with:
        repository: gitlab.com/ShwetaKhai/jenkins-app-deployment-firebase.git
        token: ${{ secrets.GITLAB_TOKEN }}

    # Add your other steps for the build process here..
