name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone private repo
      run: git clone "https://gitlab.com/ShwetaKhai/jenkins-app-deployment-firebase.git"
      env:
        EXTERNAL_TOKEN : ${{ secrets.GITLAB_TOKEN }}

    
    # Add your other steps for the build process here.
